version: "3.9"

services:
  grpc-mixed-genre-analysis:
    build:
      context: ..
      dockerfile: docker/Dockerfile.grpc_mixed.genre_cpp
    container_name: grpc-mixed-genre-analysis
    ports:
      - "50055:50055"
    networks:
      - grpc-network
    restart: unless-stopped

  grpc-mixed-recommendation:
    build:
      context: ..
      dockerfile: docker/Dockerfile.grpc_mixed.recommendation_go
    container_name: grpc-mixed-recommendation
    ports:
      - "50057:50057"
    networks:
      - grpc-network
    restart: unless-stopped

  grpc-mixed-userbehavior:
    build:
      context: ..
      dockerfile: docker/Dockerfile.grpc_mixed.userbehavior
    container_name: grpc-mixed-userbehavior
    environment:
      - USERBEHAVIOR_PORT=50053
      - GENRE_ANALYSIS_ADDRESS=grpc-genre-analysis:50055
    ports:
      - "50053:50053"
    networks:
      - grpc-network
    restart: unless-stopped
    depends_on:
      - grpc-mixed-genre-analysis

  grpc-mixed-mapreduce:
    build:
      context: ..
      dockerfile: docker/Dockerfile.grpc_mixed.mapreduce
    container_name: grpc-mixed-mapreduce
    environment:
      - MAPREDUCE_PORT=50051
      - USERBEHAVIOR_ADDRESS=grpc-userbehavior:50053
    ports:
      - "50051:50051"
    networks:
      - grpc-network
    restart: unless-stopped
    depends_on:
      - grpc-mixed-userbehavior

  grpc-mixed-client:
    build:
      context: ..
      dockerfile: docker/Dockerfile.grpc_mixed.client
    container_name: grpc-mixed-client
    environment:
      - MAPREDUCE_HOST=grpc-mixed-mapreduce
      - MAPREDUCE_PORT=50051
      - USERBEHAVIOR_HOST=grpc-mixed-userbehavior
      - USERBEHAVIOR_PORT=50053
      - GENRE_ANALYSIS_HOST=grpc-mixed-genre-analysis
      - GENRE_ANALYSIS_PORT=50055
      - RECOMMENDATION_HOST=grpc-mixed-recommendation
      - RECOMMENDATION_PORT=50057
      - RESULTS_DIR=/app/grpc-mixed/results
    depends_on:
      - grpc-mixed-mapreduce
      - grpc-mixed-userbehavior
      - grpc-mixed-genre-analysis
      - grpc-mixed-recommendation
    networks:
      - grpc-network
    volumes:
      - ./grpc-mixed/results:/app/grpc-mixed/results
    restart: "no"

networks:
  grpc-network:
    driver: bridge
